export const REQUESTED_FIRST_QUESTION = 'REQUESTED_FIRST_QUESTION';
export const REQUESTED_NEXT_QUESTION = 'REQUESTED_NEXT_QUESTION';
export const SELECTED_ANSWER = 'SELECTED_ANSWER';
export const TOGGLED_NEXT_READY = 'TOGGLED_NEXT_READY';
